name: Bug report
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      placeholder: Describe the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: "1) ...\n2) ...\n3) ..."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / commit
      placeholder: "main @ <short-sha>"
